---
- name: Read the current default target
  ansible.builtin.command: systemctl get-default
  register: default_target_now
  changed_when: false
  check_mode: false
  tags:
    - default_target

- name: Set the default target
  ansible.builtin.command: "systemctl set-default {{ default_target }}"
  when: default_target_now.stdout | trim != default_target
  changed_when: true
  tags:
    - default_target
