---
- name: Assert that variables are defined
  ansible.builtin.fail:
    msg: "Variable '{{ item }}' is not defined"
  when: item not in vars
  with_items:
    - nis_domain
    - nis_server

- name: Prevent daemons from starting when installing packages, particularly ypbind
  ansible.builtin.copy:
    src: policy-rc.d
    dest: /usr/sbin/policy-rc.d
    owner: root
    group: root
    mode: "0700"
  changed_when: false

- name: Install Ubuntu packages
  ansible.builtin.apt: name=nis,rpcbind state=present
  when: ansible_os_family == "Debian"

- name: Install CentOS NIS packages
  ansible.builtin.dnf: name=ypbind state=present
  when: ansible_os_family == "RedHat"

- name: Ensure rpcbind is running
  ansible.builtin.service: name=rpcbind state=started enabled=true

- name: Set server
  ansible.builtin.lineinfile:
    dest: /etc/yp.conf
    regexp: "^domain"
    line: "domain {{ nis_domain }} server {{ nis_server }}"
  notify: "Restart nis"

- name: Create default domain name file
  ansible.builtin.file:
    path: /etc/defaultdomain
    owner: root
    group: root
    mode: "0644"
    state: touch
  changed_when: false

- name: Configure yp domainname
  ansible.builtin.lineinfile:
    dest: /etc/defaultdomain
    regexp: "^"
    line: "{{ nis_domain }}"
  notify: "Restart nis"

- name: Configure nsswitch.conf
  ansible.builtin.lineinfile:
    dest: /etc/nsswitch.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: "^passwd", line: "passwd: files nis" }
    - { regexp: "^group", line: "group: files nis" }
    - { regexp: "^shadow", line: "shadow: files nis" }
    - { regexp: "^automount", line: "automount: files nis" }
  notify: "Restart nis"

- name: Make sure rpcbind is running
  ansible.builtin.service: name=rpcbind state=started enabled=true

- name: Make sure ypbind is running on Debian
  ansible.builtin.service: name=nis state=started enabled=true
  when: ansible_os_family == "Debian"

# ypbind will not successfull start on RedHat if there's no NIS server to
# bind to, so we skip this in Molecule tests
- name: Make sure ypbind is running on RedHat
  ansible.builtin.service:
    name: ypbind
    state: started
    enabled: true
    daemon_reload: true
  when: ansible_os_family == "RedHat"
  tags:
    - molecule-notest

- name: Remove file to prevent starting services at install time
  ansible.builtin.file:
    path: /usr/sbin/policy-rc.d
    state: absent
  changed_when: false
