---
# set gpu clocks on all worker nodes
- hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Set the gpu clock to a specified amount
      ansible.builtin.shell: "nvidia-smi -lgc {{ gpu_clock_lock }}"
      when: not gpu_clock_reset

    - name: Reset the gpu clock to the default
      ansible.builtin.shell: "nvidia-smi -rgc"
      when: gpu_clock_reset
