---
- name: Get hostname
  ansible.builtin.shell: hostname
  register: hostname

- name: Check mlxconfig
  become: true
  ansible.builtin.shell: "mlxconfig query  | egrep -e Device\\|LINK_TYPE_P1\\|LINK_TYPE_P2"
  register: mlx_config
  ignore_errors: true

- name: Check ibstat
  become: true
  ansible.builtin.shell: "ibstat | egrep -e mlx\\|Link"
  register: ibstat
  ignore_errors: true

- name: Save actual hostname
  ansible.builtin.shell: echo "{{ hostname.stdout }}" >> "{{ fw_dir }}/{{ inventory_hostname }}.log"
- name: Save mlx_config
  ansible.builtin.shell: echo "{{ mlx_config.stdout }}" >> "{{ fw_dir }}/{{ inventory_hostname }}.log"
- name: Save ibstat
  ansible.builtin.shell: echo "{{ ibstat.stdout }}" >> "{{ fw_dir }}/{{ inventory_hostname }}.log"
