---
- name: Check if we are running on DGX
  ansible.builtin.stat:
    path: "/etc/dgx-release"
  register: is_dgx

- name: DGX install tasks
  ansible.builtin.include_tasks: install-dgx.yml
  when:
    - nvidia_cuda_install | bool
    - is_dgx.stat.exists

- name: Ubuntu install tasks
  ansible.builtin.include_tasks: install-ubuntu.yml
  when:
    - nvidia_cuda_install | bool
    - ansible_distribution == "Ubuntu"
    - not is_dgx.stat.exists

- name: RedHat family install tasks
  ansible.builtin.include_tasks: install-redhat.yml
  when:
    - nvidia_cuda_install | bool
    - ansible_os_family == "RedHat"
    - not is_dgx.stat.exists

- name: Add profile script to set environment for toolkit
  ansible.builtin.copy:
    src: "cuda-vars.sh"
    dest: "/etc/profile.d/cuda-vars.sh"
    owner: "root"
    group: "root"
    mode: "0644"
  when:
    - nvidia_cuda_install | bool
    - cuda_toolkit_add_profile_script | bool
