---
- name: Verify
  hosts: all
  tasks:
    - name: Check for path to singularity
      ansible.builtin.command: which singularity
      register: which_singularity
      changed_when: which_singularity.rc != 0

    - name: Verify path to singularity
      ansible.builtin.assert:
        that:
          - "'/usr/local/bin/singularity' in which_singularity.stdout"
