---
- name: Assert that variables are defined
  ansible.builtin.fail:
    msg: "Variable '{{ item }}' is not defined"
  when: item not in vars
  with_items:
    - dns_config_servers

- name: Disable services (xenial)
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop:
    - resolvconf
    - systemd-resolved
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == '16'

- name: Disable services (bionic, focal)
  ansible.builtin.service:
    name: systemd-resolved
    state: stopped
    enabled: false
  when: ansible_distribution == 'Ubuntu' and (ansible_distribution_major_version in ['18', '20'])

- name: Install /etc/resolv.conf
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: "0644"

- name: Update /etc/nsswitch.conf
  ansible.builtin.lineinfile:
    path: /etc/nsswitch.conf
    regexp: "^hosts:"
    line: "hosts: files dns"
