---
- name: Kill user processes for {{ user }}
  ansible.builtin.command: killall -u {{ user }}
  register: kill_user_procs
  failed_when: false
  changed_when: kill_user_procs.rc == 0

- name: Move home directory for {{ user }}
  ansible.builtin.user:
    name: "{{ user }}"
    home: "{{ move_home_dirs_new_root }}/{{ user }}"
    move_home: true
