# We cannot move the home directory of the currently logged in user
# So, we create a temporary user and login with that

---
- name: Create {{ move_home_dirs_new_root }}
  ansible.builtin.file:
    path: "{{ move_home_dirs_new_root }}"
    mode: "0755"
    state: directory

- name: Set key path
  ansible.builtin.set_fact:
    tmp_user_key_path: /tmp/ssh-key-for-ansible-move-home-dirs

- name: Generate key for temporary user
  ansible.builtin.command: ssh-keygen -q -t rsa -f "{{ tmp_user_key_path }}" -C "" -N ""
  args:
    creates: "{{ tmp_user_key_path }}"
  delegate_to: 127.0.0.1
  become: false
  run_once: true

- name: Delete temporary user
  ansible.builtin.user:
    name: "{{ tmp_user }}"
    state: absent
    remove: true
    force: true

- name: Create temporary user
  ansible.builtin.user:
    name: "{{ tmp_user }}"
    home: "{{ move_home_dirs_new_root }}/{{ tmp_user }}"

- name: Add new key for temporary user
  ansible.posix.authorized_key:
    user: "{{ tmp_user }}"
    key: "{{ lookup('file', tmp_user_key_path + '.pub') }}"

- name: Grant sudo to temporary user
  ansible.builtin.copy:
    content: "{{ tmp_user }} ALL=(ALL) NOPASSWD:ALL"
    dest: "/etc/sudoers.d/{{ tmp_user }}"
    mode: "0700"

# Useful for slurm clusters
- name: Grant SSH access to temporary user
  ansible.builtin.lineinfile:
    path: /etc/localusers
    line: "{{ tmp_user }}"
    create: true
    mode: "0644"

- name: Move each user
  ansible.builtin.include_tasks: move_user.yml
  vars:
    ansible_user: "{{ tmp_user }}"
    ansible_ssh_private_key_file: "{{ tmp_user_key_path }}"
  loop: "{{user_list.stdout_lines}}"
  loop_control:
    loop_var: user

- name: Revoke SSH access from temporary user
  ansible.builtin.lineinfile:
    path: /etc/localusers
    line: "{{ tmp_user }}"
    state: absent

- name: Revoke sudo for temporary user
  ansible.builtin.file:
    path: "/etc/sudoers.d/{{ tmp_user }}"
    state: absent

- name: Delete temporary user
  ansible.builtin.user:
    name: "{{ tmp_user }}"
    state: absent
    remove: true
    force: true
