---
- name: Create config dir
  ansible.builtin.file:
    path: "{{ alertmanager_config_dir }}"
    state: directory
    mode: "0755"

- name: Install config file
  ansible.builtin.template:
    src: "{{ alertmanager_config_src }}"
    dest: "{{ alertmanager_config_dir }}/alertmanager.yml"
    owner: root
    group: root
    mode: "0644"
  notify: Restart alertmanager

- name: Install python3 docker module
  ansible.builtin.package:
    name: python3-docker
    state: present

- name: Create a persistent docker volume for metrics
  community.docker.docker_volume:
    name: "{{ alertmanager_docker_volume_name }}"
    state: "present"

- name: Install systemd unit file
  ansible.builtin.template:
    src: templates/docker.alertmanager.service.j2
    dest: "/etc/systemd/system/{{ alertmanager_svc_name }}"
    owner: root
    group: root
    mode: "0644"
  notify: Restart alertmanager

- name: Configure service
  ansible.builtin.systemd:
    name: "{{ alertmanager_svc_name }}"
    state: "{{ alertmanager_state }}"
    enabled: "{{ alertmanager_enabled }}"
    daemon_reload: true
  notify: Restart alertmanager
