---
# Tasks for Master node
- name: Install Openshift pip module
  ansible.builtin.pip:
    name: openshift
  tags:
    - roce_k8s

- name: Check for module openshift
  community.general.python_requirements_facts:
    dependencies:
      - openshift
  tags:
    - roce_k8s

# Create configmap for SRIOV device plugin

- name: Create configmap
  kubernetes.core.k8s:
    state: present
    definition:
      kind: ConfigMap
      apiVersion: v1
      metadata:
        name: sriovdp-config
        namespace: kube-system
      data:
        config.json: "{{ lookup('template', 'config_dp.j2') | from_yaml | to_nice_json }}"
  run_once: true
  tags:
    - roce_k8s

# Install DP and CNI's

- name: Install Universal SR-IOV device plugin
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('url', '{{ sriov_dp_ds }}', split_lines=False) }}"
  run_once: true
  tags:
    - roce_k8s

- name: Install SR-IOV CNI
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('url', '{{ sriov_cni_ds }}', split_lines=False) }}"
  run_once: true
  tags:
    - roce_k8s

- name: Install DHCP CNI
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('url', 'https://raw.githubusercontent.com/Mellanox/dhcp-cni/master/k8s-1.16/dhcp-cni-ds.yaml', split_lines=False) }}"
  run_once: true
  tags:
    - roce_k8s

# Update Multus to latest version

- name: Multus update
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('url', '{{ multus_ds }}', split_lines=False) }}"
  run_once: true
  tags:
    - roce_k8s

- name: Wait for Multus update to settle
  ansible.builtin.pause:
    minutes: 1
  tags:
    - roce_k8s

# Create Network Attach Definitions

- name: Add NetworkAttachmentDefinition
  ansible.builtin.include_tasks: nad4roce.yaml
  with_items: "{{ sriov_resources }}"
  tags:
    - roce_k8s

# Install MPI Operator:latest

- name: Install Kubeflow MPI-Operator version v1alpha2
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('url', 'https://raw.githubusercontent.com/kubeflow/mpi-operator/master/deploy/v1/mpi-operator.yaml', split_lines=False) }}"
  run_once: true
  tags:
    - roce_k8s
