---
- name: Apt update
  ansible.builtin.apt:
    update_cache: true
  when: ansible_distribution == 'Ubuntu'

- name: Restart cachefilesd
  ansible.builtin.service:
    name: cachefilesd
    state: restarted

- name: Reboot after driver install
  ansible.builtin.reboot:
  when: install_driver.changed and not nvidia_driver_skip_reboot

- name: Restart docker
  ansible.builtin.service:
    name: docker
    state: restarted
