#
# install software modules using EasyBuild:
#
---
- name: "Install depending software"
  become: true
  ansible.builtin.apt:
    name:
      - libssl-dev
      - build-essential
      - libsysfs-dev
      - libibverbs-dev
