---
- name: Check for DGX
  when: ansible_product_name is search("DGX")
  ansible.builtin.set_fact:
    dcgm_is_dgx: true

- name: DGX tasks
  when: dcgm_is_dgx
  ansible.builtin.include_tasks: install-dgx.yml
- name: Ubuntu tasks
  when: (ansible_distribution == "Ubuntu") and not dcgm_is_dgx
  ansible.builtin.include_tasks: install-ubuntu.yml
- name: Red Hat family tasks
  when: (ansible_os_family == "RedHat") and not dcgm_is_dgx
  ansible.builtin.include_tasks: install-redhat.yml
- name: Populate service facts
  tags:
    - molecule-notest
  ansible.builtin.service_facts:

- name: Start the nvidia-dcgm service when present (preferred)
  ansible.builtin.systemd:
    daemon_reload: true
    name: "nvidia-dcgm.service"
    state: "started"
    enabled: true
  when: '"nvidia-dcgm.service" in services'
  tags:
    - molecule-notest

- name: Start the dcgm service otherwise
  ansible.builtin.systemd:
    daemon_reload: true
    name: "dcgm.service"
    state: "started"
    enabled: true
  when: '"nvidia-dcgm.service" not in services'
  tags:
    - molecule-notest
