---
- name: Install docker
  import_playbook: ../container/docker.yml

- hosts: "{{ hostlist | default('all') }}"
  become: true
  tasks:
    - name: Configure alertmanager
      ansible.builtin.include_role:
        name: alertmanager
