---
- name: Install docker
  import_playbook: ../container/docker.yml

- name: Install NVIDIA driver
  import_playbook: ../nvidia-software/nvidia-driver.yml
  when: slurm_cluster_install_nvidia_driver | default(true)

- name: Install NVIDIA container runtime
  import_playbook: ../container/nvidia-docker.yml

- hosts: "{{ hostlist | default('all') }}"
  become: true
  tasks:
    - name: Install custom facts module
      ansible.builtin.include_role:
        name: facts
    - name: Set GPU fact
      ansible.builtin.set_fact:
        has_gpus: true
      when: ansible_local['gpus']['count']
    - name: Configure dcgm exporter
      ansible.builtin.include_role:
        name: nvidia-dcgm-exporter
      when: ansible_distribution == "Ubuntu" or ansible_os_family == "RedHat"
